# Generated by Django 5.0.4 on 2024-06-25 15:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Jobs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firmname', models.CharField(max_length=100)),
                ('jobtitle', models.CharField(max_length=100)),
                ('post', models.CharField(max_length=50)),
                ('jobdesc', models.TextField()),
                ('qualification', models.CharField(max_length=100)),
                ('experience', models.CharField(max_length=20)),
                ('location', models.CharField(max_length=100)),
                ('salarypa', models.IntegerField()),
                ('posteddate', models.CharField(max_length=30)),
                ('emailaddress', models.EmailField(max_length=50)),
            ],
        ),
    ]
