# Generated by Django 5.1.7 on 2025-07-30 16:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employer', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cpname', models.TextField(default='', max_length=300)),
                ('caption', models.TextField(max_length=500)),
                ('media', models.FileField(upload_to='')),
                ('posteddate', models.CharField(default='', max_length=30)),
            ],
        ),
        migrations.AlterField(
            model_name='jobs',
            name='qualification',
            field=models.CharField(max_length=50),
        ),
    ]
