# Generated by Django 5.0.4 on 2024-08-12 08:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employer', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobs',
            name='postedby',
            field=models.CharField(default='', max_length=30),
        ),
    ]
