# Generated by Django 5.0.4 on 2024-08-12 08:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('employer', '0002_jobs_postedby'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='jobs',
            name='postedby',
        ),
    ]
