# Generated by Django 5.1.7 on 2025-08-04 06:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employer', '0002_post_alter_jobs_qualification'),
    ]

    operations = [
        migrations.CreateModel(
            name='Employer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('empprofilepic', models.ImageField(blank=True, null=True, upload_to='employer_pics/')),
                ('firmname', models.CharField(max_length=100)),
                ('firmwork', models.CharField(max_length=100)),
                ('firmaddress', models.CharField(max_length=200)),
                ('cpname', models.CharField(max_length=100)),
                ('cpcontactno', models.CharField(max_length=20)),
                ('cpemailaddress', models.EmailField(max_length=100)),
                ('aadharno', models.CharField(max_length=20)),
                ('panno', models.CharField(max_length=20)),
                ('gstno', models.CharField(max_length=20)),
                ('regdate', models.DateTimeField()),
            ],
        ),
    ]
