# Generated by Django 5.0.4 on 2024-08-14 08:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employer', '0003_remove_jobs_postedby'),
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('profilepic', models.FileField(upload_to='')),
                ('caption', models.TextField(max_length=200)),
                ('media', models.FileField(upload_to='')),
            ],
        ),
    ]
