# Generated by Django 5.0.4 on 2024-08-14 09:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employer', '0005_remove_post_profilepic_post_posteddate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='caption',
            field=models.TextField(max_length=500),
        ),
    ]
