# Generated by Django 5.0.4 on 2024-08-21 11:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('employer', '0007_post_cpemailaddress_post_cpname'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='cpemailaddress',
        ),
    ]
