# Generated by Django 5.2.4 on 2025-07-28 08:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('employer', '0010_jobs_job_tags'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='jobs',
            name='job_tags',
        ),
    ]
