# Generated by Django 5.0.4 on 2024-08-05 09:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jsapp', '0003_remove_appliedjobs_id_alter_appliedjobs_jobtitle'),
    ]

    operations = [
        migrations.AddField(
            model_name='appliedjobs',
            name='id',
            field=models.AutoField(default=1, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='appliedjobs',
            name='jobtitle',
            field=models.CharField(max_length=100),
        ),
    ]
