# Generated by Django 5.1.7 on 2025-07-30 16:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employer', '0002_post_alter_jobs_qualification'),
        ('jobapp', '0002_employer_empprofilepic_jobseeker_profilepic_and_more'),
        ('jsapp', '0004_appliedjobs_id_alter_appliedjobs_jobtitle'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appliedjobs',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.CreateModel(
            name='SavedJob',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('saved_at', models.DateTimeField(auto_now_add=True)),
                ('job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='employer.jobs')),
                ('jobseeker', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='jobapp.jobseeker')),
            ],
            options={
                'unique_together': {('jobseeker', 'job')},
            },
        ),
    ]
