# Generated by Django 5.0.4 on 2024-09-28 14:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jsapp', '0004_appliedjobs_id_alter_appliedjobs_jobtitle'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appliedjobs',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
