# Generated by Django 5.2.4 on 2025-07-28 08:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jsapp', '0006_alter_response_emailaddress_savedjob'),
    ]

    operations = [
        migrations.AlterField(
            model_name='response',
            name='emailaddress',
            field=models.CharField(max_length=50),
        ),
    ]
