# Generated by Django 5.1.7 on 2025-07-30 16:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='employer',
            name='empprofilepic',
            field=models.ImageField(default='pic', upload_to='employers/'),
        ),
        migrations.AddField(
            model_name='jobseeker',
            name='profilepic',
            field=models.ImageField(default='pic', upload_to='jobseekers/'),
        ),
        migrations.AlterField(
            model_name='employer',
            name='regdate',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='enquiry',
            name='address',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='enquiry',
            name='contactno',
            field=models.CharField(max_length=15),
        ),
        migrations.AlterField(
            model_name='enquiry',
            name='emailaddress',
            field=models.EmailField(max_length=50),
        ),
        migrations.AlterField(
            model_name='enquiry',
            name='gender',
            field=models.CharField(choices=[('Male', 'Male'), ('Female', 'Female'), ('Other', 'Other')], max_length=6),
        ),
        migrations.AlterField(
            model_name='enquiry',
            name='posteddate',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='jobseeker',
            name='dob',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='jobseeker',
            name='gender',
            field=models.CharField(choices=[('Male', 'Male'), ('Female', 'Female'), ('Other', 'Other')], max_length=6),
        ),
        migrations.AlterField(
            model_name='jobseeker',
            name='regdate',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='login',
            name='password',
            field=models.CharField(max_length=128),
        ),
    ]
