# Generated by Django 5.1.7 on 2025-08-17 07:29

import django.core.validators
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobapp', '0002_employer_empprofilepic_jobseeker_profilepic_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Administrator',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('profilepic', models.ImageField(upload_to='admin_profiles/')),
                ('fullName', models.CharField(max_length=100)),
                ('username', models.CharField(max_length=50, unique=True)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('phone', models.CharField(max_length=17, validators=[django.core.validators.RegexValidator(message="Phone number must be entered in the format: '+1234567890'. Up to 15 digits allowed.", regex='^\\+?\\d{10,15}')])),
                ('gender', models.CharField(choices=[('male', 'Male'), ('female', 'Female'), ('other', 'Other'), ('prefer_not_to_say', 'Prefer not to say')], max_length=20)),
                ('dob', models.DateField()),
                ('address', models.TextField()),
                ('city', models.CharField(max_length=50)),
                ('state', models.CharField(max_length=50)),
                ('country', models.CharField(default='India', max_length=50)),
                ('employeeId', models.CharField(max_length=20, unique=True)),
                ('department', models.CharField(choices=[('hr', 'Human Resources'), ('it', 'Information Technology'), ('finance', 'Finance'), ('operations', 'Operations'), ('management', 'Management')], max_length=20)),
                ('accessLevel', models.CharField(choices=[('super_admin', 'Super Administrator'), ('admin', 'Administrator'), ('moderator', 'Moderator')], max_length=20)),
                ('regdate', models.DateTimeField(default=django.utils.timezone.now)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Administrator',
                'verbose_name_plural': 'Administrators',
                'db_table': 'administrator',
                'ordering': ['-regdate'],
            },
        ),
    ]
