# Generated by Django 5.0.4 on 2024-08-09 10:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobapp', '0002_jobseeker_profilepic'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jobseeker',
            name='regdate',
            field=models.CharField(max_length=30),
        ),
    ]
