# Generated by Django 5.0.4 on 2024-08-09 11:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobapp', '0004_employer_empprofilepic'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employer',
            name='regdate',
            field=models.CharField(max_length=30),
        ),
    ]
